### ISSUE TITLE
Error related to matched trees (appears not to break output)

### ISSUE THREAD

**Issue by mcitron** [milliQan-sw/milliqanOffline#23]
Error in <TTreeFormula::Compile>:  Bad numerical expression : "evtNum"

when adding FriendTree

**Comment by carriganm95** [comment]
This issue is fixed by updated AddTriggerNumber.cc file in MilliDAQ repo. Problem was due to the BuildIndex function. The error no longer appears after removing the BuildIndex on eventNum. Without the index we should probably have a check on the event numbers in MilliQan and MatchedFiles to ensure they are not out of sync.

**Comment by carriganm95** [comment]
this is fixed with latest matched files and offline sw.
